### ISSUE TITLE
How could I do it?

### ISSUE THREAD

**Issue by PhillipMC** [mtuanp/packtpubbot#5]
hello, I want to download the same ebook in 2 different formats (pdf and mobi).
How could I do it? 
I've tried to change the config.json so:

{
  "informBy": "",
  "downloadAfterClaim": true,
  "outputDirectory": ".../packtpub/",
  **"dowloadFormat": "pdf",**
  "packtpub": {
    "email": "phillip******@******* . com",
    "password": "******"
  },
  "pushbullet": {
    "apiKey": "put your pushbullet api key here"
  },
    "telegram": {
    "botToken" : "put your telegram bot token here",
    "receiverId" : "put destination user id here"
  }
}

In bold above I added: "pdf", "mobi",
 "pdf mobi", 
 "mobi",
  pdf mobi,
  
Even I copied 2 times the entire config.json at the same file but it doesn't work.
How Could i do it?
thanks

**Comment by MaikeMota** [comment]
Unfortunately this is not supported. The download feature was designed to download only one type per time. As an workaround you could set two different instances of the bot with different configurations, so every one can download the file as the desired format.
 
For now, we can mark this as a feature request to be developed in the future to improving the bot's functionalities.

@mtuanp can you mark this as a feature request?

**Comment by mtuanp** [comment]
I've just added the multi file-formats download routine. @PhillipMC you add the following for downloading epub and pdf: "dowloadFormat": "epub;pdf", just separate it with ;.

**Comment by mtuanp** [comment]
@MaikeMota sorry, I (my Atom...) changed the line-ending, so the diff on the index.js is little confused. If you want I can re-commit everything.

**Comment by MaikeMota** [comment]
@mtuanp That's not a problem for me. Thanks for add this new feature.

**Comment by PhillipMC** [comment]
It´s works perfectly. Me like MaikeMota that is not a problem for me. thanks for the feature.

**Comment by mtuanp** [comment]
Ok, I close this one.
